# Self-hosted Mithril aggregator + signer (single-signer test cluster).
#
# Purpose (Phase 0f-ii of the distributed-system refactor plan): produce
# Mithril snapshots whose metadata matches what our 10.7.x cardano-node
# writes to disk. Upstream `release-preprod.api.mithril.network` runs
# cardano-node ≤10.5.1 per distribution 2537.0 release notes, so its
# snapshots lack the `tablesCodecVersion` metadata key that
# `mithril-client tools utxo-hd snapshot-converter --utxo-hd-flavor LSM`
# requires from 10.7.x+. Running our own aggregator alongside our own
# cardano-node sidesteps that version-skew entirely.
#
# Not in scope for the test cluster:
# - P2P signer discovery (single-signer by design)
# - GCP / S3 snapshot uploaders (SNAPSHOT_UPLOADER_TYPE=local)
# - Reverse proxy / Traefik (aggregator binds 0.0.0.0:8080 directly;
#   NixOS firewall opens the port)
# - Snapshot compression / CDN tuning (defaults are fine for test use)
#
# Prerequisites (one-time, manual, documented in docs/deployment.md):
# - KES secret key + operational certificate generated via cardano-cli
#   on first deploy and copied to /data/mithril/signer/{kes.skey,op.cert}.
#   KES rotation is once-per-90-day-window on preprod; a single KES
#   period covers the test cluster's lifetime.
# - Aggregator genesis keys are auto-generated on first ExecStartPre via
#   `mithril-aggregator tools genesis generate` — the public `.vkey`
#   should be copied into nix/mithril-genesis/self-hosted.vkey and
#   committed so CI's `mithril-client --genesis-verification-key` call
#   verifies against our own root of trust.
{ config, pkgs, lib, inputs, ... }:
let
  cardanoNodeBin = pkgs.callPackage ./cardano-node-bin.nix { };

  mithrilAggregator = inputs.mithril.packages.${pkgs.system}.mithril-aggregator;
  mithrilSigner = inputs.mithril.packages.${pkgs.system}.mithril-signer;

  # Preprod network magic (matches cardano-node's topology / genesis).
  networkMagic = 1;
  aggregatorPort = 8080;
  aggregatorEndpoint = "http://127.0.0.1:${toString aggregatorPort}/aggregator";

  # Launch wrapper for the aggregator: loads runtime-generated genesis
  # keys from disk into env vars before exec'ing `mithril-aggregator`.
  # Env vars (vs. --arg flags) match the upstream docker-compose surface
  # so config drift stays comprehensible when cross-referencing
  # ${inputs.mithril}/mithril-infra/assets/docker/docker-compose-aggregator-base.yaml.
  aggregatorLauncher = pkgs.writeShellScript "mithril-aggregator-run" ''
    set -eu
    export RUST_BACKTRACE=1
    export NETWORK=preprod
    export NETWORK_MAGIC=${toString networkMagic}
    export PROTOCOL_PARAMETERS__K=5
    export PROTOCOL_PARAMETERS__M=100
    export PROTOCOL_PARAMETERS__PHI_F=0.65
    export RUN_INTERVAL=60000
    export SIGNED_ENTITY_TYPES="CardanoImmutableFilesFull"
    # Valid values per upstream `aggregate_signature_type` config field:
    # `Concatenation` (default) or `BlsSum`. Default is fine; set
    # explicitly here to avoid drift.
    export AGGREGATE_SIGNATURE_TYPE=Concatenation
    export SNAPSHOT_UPLOADER_TYPE=local
    export SNAPSHOT_COMPRESSION_ALGORITHM=zstandard
    export DATA_STORES_DIRECTORY=/data/mithril/aggregator/stores
    export STORE_RETENTION_LIMIT=5
    export CARDANO_NODE_SOCKET_PATH=/data/cardano-node/node.socket
    export CARDANO_NODE_VERSION=10.7.1
    export CARDANO_CLI_PATH=${cardanoNodeBin}/bin/cardano-cli
    export CHAIN_OBSERVER_TYPE=cardano-cli
    export DB_DIRECTORY=/data/cardano-node/db
    export SNAPSHOT_DIRECTORY=/data/mithril/aggregator/snapshots
    export SERVER_PORT=${toString aggregatorPort}
    export SERVER_IP=0.0.0.0
    # Upstream `GenesisTools::create_and_save_genesis_keypair` (tools/
    # genesis.rs:218-230) writes `genesis.sk` and `genesis.vk` — NOT
    # `.skey`/`.vkey`. Must match those names or the cat fails.
    export GENESIS_VERIFICATION_KEY="$(cat /data/mithril/aggregator/genesis.vk)"
    export GENESIS_SECRET_KEY="$(cat /data/mithril/aggregator/genesis.sk)"
    # ED25519 secret for signing ancillary files (added in mithril
    # ≥0.8.x). JSON-encoded; auto-generated by PreStart if missing.
    export ANCILLARY_FILES_SIGNER_CONFIG="$(cat /data/mithril/aggregator/ancillary.json)"
    exec ${mithrilAggregator}/bin/mithril-aggregator -vvv serve
  '';

  signerLauncher = pkgs.writeShellScript "mithril-signer-run" ''
    set -eu
    export RUST_BACKTRACE=1
    export NETWORK=preprod
    export NETWORK_MAGIC=${toString networkMagic}
    export AGGREGATOR_ENDPOINT=${aggregatorEndpoint}
    export RUN_INTERVAL=120000
    export DB_DIRECTORY=/data/cardano-node/db
    export DATA_STORES_DIRECTORY=/data/mithril/signer/stores
    export STORE_RETENTION_LIMIT=5
    export CARDANO_NODE_SOCKET_PATH=/data/cardano-node/node.socket
    export CARDANO_CLI_PATH=${cardanoNodeBin}/bin/cardano-cli
    export KES_SECRET_KEY_PATH=/data/mithril/signer/kes.skey
    export OPERATIONAL_CERTIFICATE_PATH=/data/mithril/signer/op.cert
    exec ${mithrilSigner}/bin/mithril-signer -vvv
  '';

  aggregatorPreStart = pkgs.writeShellScript "mithril-aggregator-init" ''
    set -eu
    mkdir -p /data/mithril/aggregator/{snapshots,stores}

    # Genesis keys are generated once on first boot; subsequent boots
    # are no-ops. The public `.vkey` should be committed to
    # nix/mithril-genesis/self-hosted.vkey after first deploy.
    #
    # Subcommand is `genesis generate-keypair`, not `tools genesis
    # generate` — verified against upstream mithril HEAD
    # (mithril-aggregator/src/commands/genesis_command.rs:148-163, :385-388).
    # `genesis generate-keypair --target-path` writes `genesis.sk` and
    # `genesis.vk` (tools/genesis.rs:218-230). Use the same names the
    # aggregator launcher `cat`s.
    if [ ! -f /data/mithril/aggregator/genesis.sk ]; then
      ${mithrilAggregator}/bin/mithril-aggregator genesis generate-keypair \
        --target-path /data/mithril/aggregator
    fi

    # Ancillary-files signer — fresh 32-byte random ED25519 seed
    # encoded as the JSON shape aggregator expects. Regenerated here
    # if missing so deploys are self-bootstrapping.
    if [ ! -f /data/mithril/aggregator/ancillary.json ]; then
      secret_hex=$(${pkgs.coreutils}/bin/head -c 32 /dev/urandom | ${pkgs.coreutils}/bin/od -An -tx1 | ${pkgs.coreutils}/bin/tr -d ' \n')
      printf '{"type":"secret-key","secret_key":"%s"}' "$secret_hex" \
        > /data/mithril/aggregator/ancillary.json
      chmod 600 /data/mithril/aggregator/ancillary.json
    fi
  '';

  signerPreStart = pkgs.writeShellScript "mithril-signer-init" ''
    set -eu
    mkdir -p /data/mithril/signer/stores

    # KES key + op cert are provisioned manually via cardano-cli — see
    # docs/deployment.md. Fail fast at boot if they're missing so we
    # don't silently sign with wrong identity.
    if [ ! -f /data/mithril/signer/kes.skey ] || [ ! -f /data/mithril/signer/op.cert ]; then
      echo "mithril-signer: missing KES key or op cert at /data/mithril/signer/" >&2
      echo "Provision via cardano-cli per docs/deployment.md before starting." >&2
      exit 1
    fi
  '';
in
{
  # Open the aggregator port so our laptop / CI can pull snapshots via
  # `mithril-client --aggregator-endpoint http://decentralizationmaxi.io:8080/aggregator`.
  networking.firewall.allowedTCPPorts = [ aggregatorPort ];

  systemd.tmpfiles.rules = [
    "d /data/mithril 0755 root root -"
    "d /data/mithril/aggregator 0755 root root -"
    "d /data/mithril/signer 0755 root root -"
  ];

  systemd.services.mithril-aggregator = {
    description = "Mithril aggregator (self-hosted, preprod)";
    # Self-bootstrapping: aggregatorPreStart auto-generates the genesis
    # keypair (`genesis.sk` / `genesis.vk`) and the ancillary-files
    # signer JSON (`ancillary.json`) on first boot, so the aggregator
    # can start cleanly without manual provisioning.
    wantedBy = [ "multi-user.target" ];
    after = [ "cardano-node.service" ];
    requires = [ "cardano-node.service" ];
    unitConfig.ConditionPathExists = "/data/cardano-node/node.socket";
    serviceConfig = {
      ExecStartPre = aggregatorPreStart;
      ExecStart = aggregatorLauncher;
      Restart = "on-failure";
      RestartSec = 30;
    };
  };

  systemd.services.mithril-signer = {
    description = "Mithril signer (self-hosted, preprod)";
    # Intentionally NOT `wantedBy = [ "multi-user.target" ]` — the unit
    # is installed but not auto-started at boot. KES secret key + op
    # cert must be provisioned manually into /data/mithril/signer/
    # first (see docs/deployment.md), then enable via:
    #   systemctl enable --now mithril-signer
    # Without the files, PreStart fails → systemd reports the unit
    # failed → deploy-rs `autoRollback` reverts the whole switch.
    wantedBy = [ ];
    after = [ "mithril-aggregator.service" ];
    requires = [ "mithril-aggregator.service" ];
    serviceConfig = {
      ExecStartPre = signerPreStart;
      ExecStart = signerLauncher;
      Restart = "on-failure";
      RestartSec = 30;
    };
  };
}
