import { Effect, Option, Schema, SchemaAST as AST, SchemaIssue } from "effect";
import type * as FastCheck from "effect/testing/FastCheck";
import {
  cborCodec,
  cborTaggedLink,
  cborUintCodec,
  CborKinds,
  type CborSchemaType,
  positionalArrayLink,
  toCodecCborBytes,
  withCborLink,
} from "codecs";
import { expectUint, uint } from "./cbor-utils.ts";

// ────────────────────────────────────────────────────────────────────────────
// Branded numeric primitives (all non-negative bigint, CBOR: uint)
// CDDL bound: `uint .size 8` = Word64 = [0, 2^64 − 1].
// ────────────────────────────────────────────────────────────────────────────

export const MAX_WORD64 = 2n ** 64n - 1n;

const Word64 = Schema.BigInt.pipe(
  Schema.check(Schema.isBetweenBigInt({ minimum: 0n, maximum: MAX_WORD64 })),
);

export const Coin = Word64.pipe(Schema.brand("Coin"));
export type Coin = typeof Coin.Type;

export const Slot = Word64.pipe(Schema.brand("Slot"));
export type Slot = typeof Slot.Type;

export const Epoch = Word64.pipe(Schema.brand("Epoch"));
export type Epoch = typeof Epoch.Type;

export const Ix = Word64.pipe(Schema.brand("Ix"));
export type Ix = typeof Ix.Type;

// ────────────────────────────────────────────────────────────────────────────
// Network enum
// ────────────────────────────────────────────────────────────────────────────

export enum Network {
  Testnet = 0,
  Mainnet = 1,
}

export const NetworkSchema = Schema.Enum(Network);
export type NetworkType = typeof NetworkSchema.Type;

// ────────────────────────────────────────────────────────────────────────────
// Rational number
// ────────────────────────────────────────────────────────────────────────────

// CBOR wire: Tag(30, [numerator, denominator]). The custom link composes
// `positionalArrayLink` (the Struct-to-Array layer) with `cborTaggedLink(30n)`
// (the outer Tag wrapper); composition pattern: build the inner link first,
// splice it onto the walked AST via `AST.replaceEncoding`, then ask
// `cborTaggedLink` to read it back as the tag's payload.
//
// CDDL §589 nonnegative_interval = #6.30([uint, positive_int])
//   where positive_int = 1 .. max_word64.
// Both slots are non-negative; the denominator is strictly positive.
// Explicit `toArbitrary` generates valid values by construction — a
// rejection filter on `denominator > 0` would thrash fast-check's shrinker.
export const Rational = Schema.Struct({
  numerator: Schema.BigInt.pipe(
    Schema.check(Schema.isBetweenBigInt({ minimum: 0n, maximum: MAX_WORD64 })),
  ),
  denominator: Schema.BigInt.pipe(
    Schema.check(Schema.isBetweenBigInt({ minimum: 1n, maximum: MAX_WORD64 })),
  ),
}).pipe(
  Schema.annotate({
    toArbitrary: () => (fc: typeof FastCheck) =>
      fc
        .tuple(fc.bigInt({ min: 0n, max: MAX_WORD64 }), fc.bigInt({ min: 1n, max: MAX_WORD64 }))
        .map(([numerator, denominator]) => ({ numerator, denominator })),
  }),
  withCborLink((walked) => {
    const positional = positionalArrayLink(["numerator", "denominator"])(walked);
    return cborTaggedLink(30n)(AST.replaceEncoding(walked, [positional]));
  }),
);
export type Rational = typeof Rational.Type;

// UnitInterval: rational in [0, 1]. Generated by construction: pick
// denominator ∈ [1, 2^64−1], then numerator ∈ [0, denominator].
export const UnitInterval = Rational.check(
  Schema.makeFilter<Rational>((r) => r.numerator <= r.denominator, {
    expected: "rational in [0, 1]",
  }),
).pipe(
  Schema.annotate({
    toArbitrary: () => (fc: typeof FastCheck) =>
      fc
        .bigInt({ min: 1n, max: MAX_WORD64 })
        .chain((denominator) =>
          fc.bigInt({ min: 0n, max: denominator }).map((numerator) => ({ numerator, denominator })),
        ),
  }),
);
export type UnitInterval = typeof UnitInterval.Type;

// ────────────────────────────────────────────────────────────────────────────
// ExUnits (execution units: memory + CPU steps)
// ────────────────────────────────────────────────────────────────────────────

// CBOR wire: [mem, steps] positional array.
export const ExUnits = Schema.Struct({
  mem: Schema.BigInt.pipe(Schema.check(Schema.isGreaterThanOrEqualToBigInt(0n))),
  steps: Schema.BigInt.pipe(Schema.check(Schema.isGreaterThanOrEqualToBigInt(0n))),
}).pipe(withCborLink((walked) => positionalArrayLink(["mem", "steps"])(walked)));
export type ExUnits = typeof ExUnits.Type;

// ────────────────────────────────────────────────────────────────────────────
// CBOR Codecs
// ────────────────────────────────────────────────────────────────────────────

export const CoinBytes = cborUintCodec(Coin, "Coin");
export const SlotBytes = cborUintCodec(Slot, "Slot");
export const EpochBytes = cborUintCodec(Epoch, "Epoch");
export const IxBytes = cborUintCodec(Ix, "Ix");

export const NetworkBytes = cborCodec(
  NetworkSchema,
  (cbor: CborSchemaType) =>
    Effect.gen(function* () {
      const n = Number(yield* expectUint(cbor, "Network"));
      switch (n) {
        case Network.Testnet:
          return Network.Testnet;
        case Network.Mainnet:
          return Network.Mainnet;
        default:
          return yield* Effect.fail(
            new SchemaIssue.InvalidValue(Option.some(cbor), {
              message: `Network: unknown value ${n}`,
            }),
          );
      }
    }),
  (net) => Effect.succeed(uint(net)),
);

// Rational: CBOR Tag(30, [numerator, denominator]) — derived via Phase 0a
// compositeLinks (`positionalArrayLink` + `cborTaggedLink(30n)`).
export const RationalBytes = toCodecCborBytes(Rational);

// ExUnits: CBOR [mem, steps] — derived via positionalArrayLink.
export const ExUnitsBytes = toCodecCborBytes(ExUnits);
