/**
 * Golden cryptographic test vectors — ported from Amaru and Dingo.
 *
 * Tests real VRF, KES, and Ed25519 operations against known-good values
 * generated by Haskell (Amaru test-vector.json) and Go (Dingo keys_test.go).
 *
 * Requires WASM crypto (CryptoDirect) — skip in environments without it.
 */
import { describe, it, expect } from "@effect/vitest";
import { Effect } from "effect";
import {
  Crypto,
  CryptoDirect,
  ed25519_sign,
  ed25519_public_key,
  ed25519_secret_key_from_seed,
} from "wasm-utils";

const provide = <A>(effect: Effect.Effect<A, unknown, Crypto>) =>
  effect.pipe(Effect.provide(CryptoDirect));

// --- Amaru KES golden vectors ---
// Source: amaru/crates/amaru-ouroboros/src/kes/mod.rs kes_signature_verify
// Extracted directly from Rust source with line-continuation stripping.
const KES_VECTORS = {
  publicKey: "2e5823037de29647e495b97d9dd7bf739f7ebc11d3701c8d0720f55618e1b292",
  period: 36,
  // 448 bytes = Sum6KES signature
  signature:
    "20f1c8f9ae672e6ec75b0aa63a85e7ab7865b95f6b2907a26b54c14f49184ab5" +
    "2cf98ef441bb71de50380325b34f16d84fc78d137467a1b49846747cf8ee4701c" +
    "56f08f198b94c468d46b67b271f5bc30ab2ad14b1bdbf2be0695a00fe4b02b306" +
    "0fa52128f4cce9c5759df0ba8d71fe99456bd2e333671e45110908d03a2ec3b38" +
    "599d26adf182ba63f79900fdb2732947cf8e940a4cf1e8db9b4cf4c001dbd37c6" +
    "0d0e38851de4910807896153be455e13161342d4c6f7bb3e4d2d35dbbbba0ebcd" +
    "161be2f1ec030d2f5a6059ac89dfa70dc6b3d0bc2da179c62ae95c4f9c7ad9c03" +
    "87b35bf2b45b325d1e0a18c0c783a0779003bf23e7a6b00cc126c5e3d51a57d41" +
    "ff1707a76fb2c306a67c21473b41f1d9a7f64a670ec172a2421da03d796fa9708" +
    "6de8812304f4f96bd45243d0a2ad6c48a69d9e2c0afbb1333acee607d18eb3a33" +
    "818c3c9d5bb72cade889379008bf60d436298cb0cfc6159332cb1af1de4f1d64e" +
    "79c399d058ac4993704eed67917093f89db6cde830383e69aa400ba3225087caba" +
    "d45407b891416330485891dc9a3875488a26428d20d581b629a8f4f42e3aa00cbc" +
    "aae6c8e2b8f3fe033b874d1de6a3f8c321c92b77643f00d28e",
  // 407 bytes = CBOR-encoded Babbage header body (the KES-signed message)
  message:
    "8a1a00a50f121a0802d24458203deea82abe788d260b8987a522aadec86c9f098e" +
    "88a57d7cfcdb24f474a7afb65820cad3c900ca6baee9e65bf61073d900bfbca458" +
    "eeca6d0b9f9931f5b1017a8cd65820576d49e98adfab65623dc16f9fff2edd210e" +
    "8dd1d4588bfaf8af250beda9d3c7825840d944b8c81000fc1182ec02194ca9eca5" +
    "10fd84995d22bfe1842190b39d468e5ecbd863969e0c717b0071a371f748d44c89" +
    "5fa9233094cefcd3107410baabb19a5850f2a29f985d37ca8eb671c2847fab9cc4" +
    "5c93738a430b4e43837e7f33028b190a7e55152b0e901548961a66d56eebe72d61" +
    "6f9e68fd13e9955ccd8611c201a5b422ac8ef56af74cb657b5b868ce9d850f1945" +
    "d15820639d4986d17de3cac8079a3b25d671f339467aa3a9948e29992dafebf90f" +
    "719f8458202e5823037de29647e495b97d9dd7bf739f7ebc11d3701c8d0720f556" +
    "18e1b292171903e958401feeeabc7460b19370f4050e986b558b149fdc8724b4a4" +
    "805af8fe45c8e7a7c6753894ad7a1b9c313da269ddc5922e150da3b378977f1dfe" +
    "a79fc52fd2c12f08820901",
};

describe("Golden crypto vectors (WASM)", () => {
  describe("blake2b-256", () => {
    it.effect("empty input matches known hash", () =>
      provide(
        Effect.gen(function* () {
          const crypto = yield* Crypto;
          const hash = yield* crypto.blake2b256(new Uint8Array(0));
          // blake2b-256("") = 0e5751c026e543b2e8ab2eb06099daa1d1e5df47778f7787faab45cdf12fe3a8
          expect(hash.toHex().startsWith("0e5751c0")).toBe(true);
          expect(hash.byteLength).toBe(32);
        }),
      ),
    );

    it.effect("is deterministic across calls", () =>
      provide(
        Effect.gen(function* () {
          const crypto = yield* Crypto;
          const input = new Uint8Array([0xca, 0xfe, 0xba, 0xbe]);
          const h1 = yield* crypto.blake2b256(input);
          const h2 = yield* crypto.blake2b256(input);
          expect(h1.toHex()).toBe(h2.toHex());
        }),
      ),
    );
  });

  describe("ed25519 — round-trip signature verification", () => {
    it.effect("sign + verify round-trip succeeds", () =>
      provide(
        Effect.gen(function* () {
          const seed = new Uint8Array(32);
          seed[0] = 0xba;
          seed[1] = 0xbe;
          const sk = ed25519_secret_key_from_seed(seed);
          const pk = ed25519_public_key(sk);

          // Opcert-style message: 32-byte vk ∥ 4-byte seqNo ∥ 4-byte kesPeriod
          const msg = new Uint8Array(40);
          msg.set(pk, 0);
          msg[32] = 0x00;
          msg[33] = 0x00;
          msg[34] = 0x00;
          msg[35] = 0x01; // seqNo = 1
          const signature = ed25519_sign(msg, sk);

          const crypto = yield* Crypto;
          const valid = yield* crypto.ed25519Verify(msg, signature, pk);
          expect(valid).toBe(true);
        }),
      ),
    );

    it.effect("rejects tampered signature (XOR first 2 bytes — Dingo pattern)", () =>
      provide(
        Effect.gen(function* () {
          const seed = new Uint8Array(32);
          seed[0] = 0xca;
          const sk = ed25519_secret_key_from_seed(seed);
          const pk = ed25519_public_key(sk);
          const msg = new TextEncoder().encode("test opcert message");
          const signature = ed25519_sign(msg, sk);

          // Tamper: XOR first 2 bytes (Dingo verify_header_test.go pattern)
          const sigView = new DataView(signature.buffer);
          sigView.setUint8(0, sigView.getUint8(0) ^ 0xff);
          sigView.setUint8(1, sigView.getUint8(1) ^ 0xff);

          const crypto = yield* Crypto;
          const valid = yield* crypto.ed25519Verify(msg, signature, pk);
          expect(valid).toBe(false);
        }),
      ),
    );

    it.effect("rejects wrong public key", () =>
      provide(
        Effect.gen(function* () {
          const seed1 = new Uint8Array(32);
          seed1[0] = 1;
          const sk1 = ed25519_secret_key_from_seed(seed1);

          const seed2 = new Uint8Array(32);
          seed2[0] = 2;
          const pk2 = ed25519_public_key(ed25519_secret_key_from_seed(seed2));

          const msg = new TextEncoder().encode("cross-key test");
          const signature = ed25519_sign(msg, sk1);

          const crypto = yield* Crypto;
          const valid = yield* crypto.ed25519Verify(msg, signature, pk2);
          expect(valid).toBe(false);
        }),
      ),
    );
  });

  describe("VRF — proof rejection", () => {
    it.effect("rejects random proof bytes", () =>
      provide(
        Effect.gen(function* () {
          const crypto = yield* Crypto;
          const exit = yield* Effect.exit(
            crypto.vrfVerifyProof(
              new Uint8Array(32).fill(0x01),
              new Uint8Array(80).fill(0x02),
              new Uint8Array(32).fill(0x03),
            ),
          );
          expect(exit._tag).toBe("Failure");
        }),
      ),
    );

    it.effect("vrfProofToHash returns 64 bytes or throws on invalid proof", () =>
      provide(
        Effect.gen(function* () {
          const crypto = yield* Crypto;
          const exit = yield* Effect.exit(crypto.vrfProofToHash(new Uint8Array(80)));
          const byteLength = exit._tag === "Success" ? exit.value.byteLength : -1;
          expect(byteLength === 64 || byteLength === -1).toBe(true);
        }),
      ),
    );
  });

  describe("KES Sum6 — signature verification (Amaru vectors)", () => {
    it.effect("verifies real KES signature at period 36", () =>
      provide(
        Effect.gen(function* () {
          const crypto = yield* Crypto;
          const valid = yield* crypto.kesSum6Verify(
            Uint8Array.fromHex(KES_VECTORS.signature),
            KES_VECTORS.period,
            Uint8Array.fromHex(KES_VECTORS.publicKey),
            Uint8Array.fromHex(KES_VECTORS.message),
          );
          expect(valid).toBe(true);
        }),
      ),
    );

    it.effect("rejects KES signature at wrong period", () =>
      provide(
        Effect.gen(function* () {
          const crypto = yield* Crypto;
          const valid = yield* crypto.kesSum6Verify(
            Uint8Array.fromHex(KES_VECTORS.signature),
            KES_VECTORS.period + 1,
            Uint8Array.fromHex(KES_VECTORS.publicKey),
            Uint8Array.fromHex(KES_VECTORS.message),
          );
          expect(valid).toBe(false);
        }),
      ),
    );

    it.effect("rejects KES signature with tampered message", () =>
      provide(
        Effect.gen(function* () {
          const tampered = Uint8Array.fromHex(KES_VECTORS.message);
          new DataView(tampered.buffer).setUint8(
            0,
            new DataView(tampered.buffer).getUint8(0) ^ 0xff,
          );

          const crypto = yield* Crypto;
          const valid = yield* crypto.kesSum6Verify(
            Uint8Array.fromHex(KES_VECTORS.signature),
            KES_VECTORS.period,
            Uint8Array.fromHex(KES_VECTORS.publicKey),
            tampered,
          );
          expect(valid).toBe(false);
        }),
      ),
    );

    it.effect("rejects KES signature with wrong public key", () =>
      provide(
        Effect.gen(function* () {
          const wrongPk = Uint8Array.fromHex(KES_VECTORS.publicKey);
          new DataView(wrongPk.buffer).setUint8(0, new DataView(wrongPk.buffer).getUint8(0) ^ 0xff);

          const crypto = yield* Crypto;
          const valid = yield* crypto.kesSum6Verify(
            Uint8Array.fromHex(KES_VECTORS.signature),
            KES_VECTORS.period,
            wrongPk,
            Uint8Array.fromHex(KES_VECTORS.message),
          );
          expect(valid).toBe(false);
        }),
      ),
    );
  });

  describe("checkVrfLeader — threshold math", () => {
    // VRF output is 64 bytes = 128 hex chars
    it.effect("accepts pool with 100% stake (Dingo pattern)", () =>
      provide(
        Effect.gen(function* () {
          const crypto = yield* Crypto;
          const lowVrf = "0".repeat(127) + "1";
          const isLeader = yield* crypto.checkVrfLeader(
            lowVrf,
            "1000000000",
            "1000000000",
            "5",
            "100",
          );
          expect(isLeader).toBe(true);
        }),
      ),
    );

    it.effect("rejects pool with 0 stake", () =>
      provide(
        Effect.gen(function* () {
          const crypto = yield* Crypto;
          // Even with low VRF output, 0 stake should never be leader
          const lowVrf = "0".repeat(127) + "1";
          const isLeader = yield* crypto.checkVrfLeader(lowVrf, "0", "1000000000", "5", "100");
          expect(isLeader).toBe(false);
        }),
      ),
    );

    it.effect("accepts high-stake pool with low VRF output", () =>
      provide(
        Effect.gen(function* () {
          const crypto = yield* Crypto;
          const lowVrf = "0".repeat(127) + "1";
          const isLeader = yield* crypto.checkVrfLeader(lowVrf, "9000000", "10000000", "5", "100");
          expect(isLeader).toBe(true);
        }),
      ),
    );

    it.effect("leader check is deterministic for same inputs", () =>
      provide(
        Effect.gen(function* () {
          const crypto = yield* Crypto;
          const vrf = "0".repeat(127) + "1";
          const a = yield* crypto.checkVrfLeader(vrf, "5000000", "10000000", "5", "100");
          const b = yield* crypto.checkVrfLeader(vrf, "5000000", "10000000", "5", "100");
          expect(a).toBe(b);
        }),
      ),
    );
  });
});
