/**
 * Golden cryptographic test vectors — ported from Amaru and Dingo.
 *
 * Tests real VRF, KES, and Ed25519 operations against known-good values
 * generated by Haskell (Amaru test-vector.json) and Go (Dingo keys_test.go).
 *
 * Requires WASM crypto (CryptoServiceLive) — skip in environments without it.
 */
import { describe, it, expect } from "vitest";
import { Effect, Layer } from "effect";
import { CryptoService, CryptoServiceLive } from "../crypto";
import { hex } from "../util";

const run = <A>(effect: Effect.Effect<A, unknown, CryptoService>) =>
  effect.pipe(Effect.provide(CryptoServiceLive), Effect.runPromise);

// --- Amaru KES golden vectors ---
// Source: amaru/crates/amaru-ouroboros/src/kes/mod.rs kes_signature_verify
// Extracted directly from Rust source with line-continuation stripping.
const KES_VECTORS = {
  publicKey: "2e5823037de29647e495b97d9dd7bf739f7ebc11d3701c8d0720f55618e1b292",
  period: 36,
  // 448 bytes = Sum6KES signature
  signature:
    "20f1c8f9ae672e6ec75b0aa63a85e7ab7865b95f6b2907a26b54c14f49184ab5" +
    "2cf98ef441bb71de50380325b34f16d84fc78d137467a1b49846747cf8ee4701c" +
    "56f08f198b94c468d46b67b271f5bc30ab2ad14b1bdbf2be0695a00fe4b02b306" +
    "0fa52128f4cce9c5759df0ba8d71fe99456bd2e333671e45110908d03a2ec3b38" +
    "599d26adf182ba63f79900fdb2732947cf8e940a4cf1e8db9b4cf4c001dbd37c6" +
    "0d0e38851de4910807896153be455e13161342d4c6f7bb3e4d2d35dbbbba0ebcd" +
    "161be2f1ec030d2f5a6059ac89dfa70dc6b3d0bc2da179c62ae95c4f9c7ad9c03" +
    "87b35bf2b45b325d1e0a18c0c783a0779003bf23e7a6b00cc126c5e3d51a57d41" +
    "ff1707a76fb2c306a67c21473b41f1d9a7f64a670ec172a2421da03d796fa9708" +
    "6de8812304f4f96bd45243d0a2ad6c48a69d9e2c0afbb1333acee607d18eb3a33" +
    "818c3c9d5bb72cade889379008bf60d436298cb0cfc6159332cb1af1de4f1d64e" +
    "79c399d058ac4993704eed67917093f89db6cde830383e69aa400ba3225087caba" +
    "d45407b891416330485891dc9a3875488a26428d20d581b629a8f4f42e3aa00cbc" +
    "aae6c8e2b8f3fe033b874d1de6a3f8c321c92b77643f00d28e",
  // 407 bytes = CBOR-encoded Babbage header body (the KES-signed message)
  message:
    "8a1a00a50f121a0802d24458203deea82abe788d260b8987a522aadec86c9f098e" +
    "88a57d7cfcdb24f474a7afb65820cad3c900ca6baee9e65bf61073d900bfbca458" +
    "eeca6d0b9f9931f5b1017a8cd65820576d49e98adfab65623dc16f9fff2edd210e" +
    "8dd1d4588bfaf8af250beda9d3c7825840d944b8c81000fc1182ec02194ca9eca5" +
    "10fd84995d22bfe1842190b39d468e5ecbd863969e0c717b0071a371f748d44c89" +
    "5fa9233094cefcd3107410baabb19a5850f2a29f985d37ca8eb671c2847fab9cc4" +
    "5c93738a430b4e43837e7f33028b190a7e55152b0e901548961a66d56eebe72d61" +
    "6f9e68fd13e9955ccd8611c201a5b422ac8ef56af74cb657b5b868ce9d850f1945" +
    "d15820639d4986d17de3cac8079a3b25d671f339467aa3a9948e29992dafebf90f" +
    "719f8458202e5823037de29647e495b97d9dd7bf739f7ebc11d3701c8d0720f556" +
    "18e1b292171903e958401feeeabc7460b19370f4050e986b558b149fdc8724b4a4" +
    "805af8fe45c8e7a7c6753894ad7a1b9c313da269ddc5922e150da3b378977f1dfe" +
    "a79fc52fd2c12f08820901",
};

describe("Golden crypto vectors (WASM)", () => {
  describe("blake2b-256", () => {
    it("empty input matches known hash", async () => {
      const hash = await run(
        Effect.gen(function* () {
          const crypto = yield* CryptoService;
          return crypto.blake2b256(new Uint8Array(0));
        }),
      );
      // blake2b-256("") = 0e5751c026e543b2e8ab2eb06099daa1d1e5df47778f7787faab45cdf12fe3a8
      expect(hex(hash).startsWith("0e5751c0")).toBe(true);
      expect(hash.byteLength).toBe(32);
    });

    it("is deterministic across calls", async () => {
      const [h1, h2] = await run(
        Effect.gen(function* () {
          const crypto = yield* CryptoService;
          const input = new Uint8Array([0xca, 0xfe, 0xba, 0xbe]);
          return [crypto.blake2b256(input), crypto.blake2b256(input)];
        }),
      );
      expect(hex(h1)).toBe(hex(h2));
    });
  });

  describe("ed25519 — round-trip signature verification", () => {
    it("sign + verify round-trip succeeds", async () => {
      const { ed25519_sign, ed25519_public_key, ed25519_secret_key_from_seed } =
        await import("wasm-utils");

      const seed = new Uint8Array(32);
      seed[0] = 0xba;
      seed[1] = 0xbe;
      const sk = ed25519_secret_key_from_seed(seed);
      const pk = ed25519_public_key(sk);

      // Opcert-style message: 32-byte vk ∥ 4-byte seqNo ∥ 4-byte kesPeriod
      const msg = new Uint8Array(40);
      msg.set(pk, 0);
      msg[32] = 0x00;
      msg[33] = 0x00;
      msg[34] = 0x00;
      msg[35] = 0x01; // seqNo = 1
      const signature = ed25519_sign(msg, sk);

      const valid = await run(
        Effect.gen(function* () {
          const crypto = yield* CryptoService;
          return crypto.ed25519Verify(msg, signature, pk);
        }),
      );
      expect(valid).toBe(true);
    });

    it("rejects tampered signature (XOR first 2 bytes — Dingo pattern)", async () => {
      const { ed25519_sign, ed25519_public_key, ed25519_secret_key_from_seed } =
        await import("wasm-utils");

      const seed = new Uint8Array(32);
      seed[0] = 0xca;
      const sk = ed25519_secret_key_from_seed(seed);
      const pk = ed25519_public_key(sk);
      const msg = new TextEncoder().encode("test opcert message");
      const signature = ed25519_sign(msg, sk);

      // Tamper: XOR first 2 bytes (Dingo verify_header_test.go pattern)
      const sigView = new DataView(signature.buffer);
      sigView.setUint8(0, sigView.getUint8(0) ^ 0xff);
      sigView.setUint8(1, sigView.getUint8(1) ^ 0xff);

      const valid = await run(
        Effect.gen(function* () {
          const crypto = yield* CryptoService;
          return crypto.ed25519Verify(msg, signature, pk);
        }),
      );
      expect(valid).toBe(false);
    });

    it("rejects wrong public key", async () => {
      const { ed25519_sign, ed25519_public_key, ed25519_secret_key_from_seed } =
        await import("wasm-utils");

      const seed1 = new Uint8Array(32);
      seed1[0] = 1;
      const sk1 = ed25519_secret_key_from_seed(seed1);

      const seed2 = new Uint8Array(32);
      seed2[0] = 2;
      const pk2 = ed25519_public_key(ed25519_secret_key_from_seed(seed2));

      const msg = new TextEncoder().encode("cross-key test");
      const signature = ed25519_sign(msg, sk1);

      const valid = await run(
        Effect.gen(function* () {
          const crypto = yield* CryptoService;
          return crypto.ed25519Verify(msg, signature, pk2);
        }),
      );
      expect(valid).toBe(false);
    });
  });

  describe("VRF — proof rejection", () => {
    it("rejects random proof bytes", async () => {
      const threw = await run(
        Effect.gen(function* () {
          const crypto = yield* CryptoService;
          try {
            crypto.vrfVerifyProof(
              new Uint8Array(32).fill(0x01),
              new Uint8Array(80).fill(0x02),
              new Uint8Array(32).fill(0x03),
            );
            return false;
          } catch {
            return true;
          }
        }),
      );
      expect(threw).toBe(true);
    });

    it("vrfProofToHash returns 64 bytes or throws on invalid proof", async () => {
      const result = await run(
        Effect.gen(function* () {
          const crypto = yield* CryptoService;
          try {
            const hash = crypto.vrfProofToHash(new Uint8Array(80));
            return hash.byteLength;
          } catch {
            return -1;
          }
        }),
      );
      expect(result === 64 || result === -1).toBe(true);
    });
  });

  describe("KES Sum6 — signature verification (Amaru vectors)", () => {
    it("verifies real KES signature at period 36", async () => {
      const valid = await run(
        Effect.gen(function* () {
          const crypto = yield* CryptoService;
          return crypto.kesSum6Verify(
            Uint8Array.fromHex(KES_VECTORS.signature),
            KES_VECTORS.period,
            Uint8Array.fromHex(KES_VECTORS.publicKey),
            Uint8Array.fromHex(KES_VECTORS.message),
          );
        }),
      );
      expect(valid).toBe(true);
    });

    it("rejects KES signature at wrong period", async () => {
      const valid = await run(
        Effect.gen(function* () {
          const crypto = yield* CryptoService;
          return crypto.kesSum6Verify(
            Uint8Array.fromHex(KES_VECTORS.signature),
            KES_VECTORS.period + 1,
            Uint8Array.fromHex(KES_VECTORS.publicKey),
            Uint8Array.fromHex(KES_VECTORS.message),
          );
        }),
      );
      expect(valid).toBe(false);
    });

    it("rejects KES signature with tampered message", async () => {
      const tampered = Uint8Array.fromHex(KES_VECTORS.message);
      new DataView(tampered.buffer).setUint8(0, new DataView(tampered.buffer).getUint8(0) ^ 0xff);

      const valid = await run(
        Effect.gen(function* () {
          const crypto = yield* CryptoService;
          return crypto.kesSum6Verify(
            Uint8Array.fromHex(KES_VECTORS.signature),
            KES_VECTORS.period,
            Uint8Array.fromHex(KES_VECTORS.publicKey),
            tampered,
          );
        }),
      );
      expect(valid).toBe(false);
    });

    it("rejects KES signature with wrong public key", async () => {
      const wrongPk = Uint8Array.fromHex(KES_VECTORS.publicKey);
      new DataView(wrongPk.buffer).setUint8(0, new DataView(wrongPk.buffer).getUint8(0) ^ 0xff);

      const valid = await run(
        Effect.gen(function* () {
          const crypto = yield* CryptoService;
          return crypto.kesSum6Verify(
            Uint8Array.fromHex(KES_VECTORS.signature),
            KES_VECTORS.period,
            wrongPk,
            Uint8Array.fromHex(KES_VECTORS.message),
          );
        }),
      );
      expect(valid).toBe(false);
    });
  });

  describe("checkVrfLeader — threshold math", () => {
    // VRF output is 64 bytes = 128 hex chars
    it("accepts pool with 100% stake (Dingo pattern)", async () => {
      const isLeader = await run(
        Effect.gen(function* () {
          const crypto = yield* CryptoService;
          const lowVrf = "0".repeat(127) + "1";
          return crypto.checkVrfLeader(lowVrf, "1000000000", "1000000000", "5", "100");
        }),
      );
      expect(isLeader).toBe(true);
    });

    it("rejects pool with 0 stake", async () => {
      const isLeader = await run(
        Effect.gen(function* () {
          const crypto = yield* CryptoService;
          // Even with low VRF output, 0 stake should never be leader
          const lowVrf = "0".repeat(127) + "1";
          return crypto.checkVrfLeader(lowVrf, "0", "1000000000", "5", "100");
        }),
      );
      expect(isLeader).toBe(false);
    });

    it("accepts high-stake pool with low VRF output", async () => {
      const isLeader = await run(
        Effect.gen(function* () {
          const crypto = yield* CryptoService;
          const lowVrf = "0".repeat(127) + "1";
          return crypto.checkVrfLeader(lowVrf, "9000000", "10000000", "5", "100");
        }),
      );
      expect(isLeader).toBe(true);
    });

    it("leader check is deterministic for same inputs", async () => {
      const [r1, r2] = await run(
        Effect.gen(function* () {
          const crypto = yield* CryptoService;
          const vrf = "0".repeat(127) + "1";
          const a = crypto.checkVrfLeader(vrf, "5000000", "10000000", "5", "100");
          const b = crypto.checkVrfLeader(vrf, "5000000", "10000000", "5", "100");
          return [a, b];
        }),
      );
      expect(r1).toBe(r2);
    });
  });
});
