/**
 * Conway UTXOW rule catalogue — failure-predicate surface.
 *
 * Wave-2 Correction #11: Conway's total failure surface is **63 predicates
 * across 4 layers**, not 19 in one type as the plan initially suggested:
 *   - ConwayUtxowPredFailure: 19 (tags 0-18)
 *   - ConwayUtxoPredFailure:  23 (tags 0-22)
 *   - ConwayUtxosPredFailure:  2 (tags 0-1)
 *   - ConwayGovPredFailure:   19 (tags 0-18)
 *
 * This file ships the **typed error surface** — a tagged-union of every
 * predicate — without the rule implementations. Implementations land
 * incrementally; callers can dispatch on `_tag` today and pattern-match
 * every variant exhaustively via `MempoolRuleError.match`.
 *
 * Each predicate is modelled as a `Schema.TaggedStruct` so it can (a) be
 * serialised across the ValidationClient RPC boundary, (b) generated by
 * `Schema.toArbitrary` for Conway §21 property tests, (c) decoded out of
 * Haskell node diagnostic streams for cross-checking.
 *
 * Source of truth (verified 2026-04-22 wave-2):
 *   ~/code/reference/IntersectMBO/cardano-ledger/eras/conway/impl/src/
 *     Cardano/Ledger/Conway/Rules/{Utxow,Utxo,Utxos,Gov}.hs
 */
import { Schema } from "effect";

// ───────────────────────────────────────────────────────────────────────
// Primitive type aliases — give semantic names to raw Schema wrappers so
// predicate fields read as `HashList` / `Lovelace` instead of repeating
// `Schema.Array(Schema.Uint8Array)` / `Schema.BigInt`. Keeps the predicate
// table legible and makes wire-format changes a one-liner.
// ───────────────────────────────────────────────────────────────────────

const Hash = Schema.Uint8Array;
const HashList = Schema.Array(Hash);
const StringList = Schema.Array(Schema.String);
const NetworkId = Schema.Number;
const Lovelace = Schema.BigInt;
const SlotNo = Schema.BigInt;
const EpochNo = Schema.BigInt;

// ───────────────────────────────────────────────────────────────────────
// Pair-shape field builders — Cardano ledger rules name both halves of
// a comparison ("declared" / "computed", "declared" / "actual",
// "declared" / "minimum", "declared" / "required", "declared" / "limit")
// and the distinction is load-bearing for error messages. Keeping each
// naming convention a named helper makes a new predicate a one-line add
// and stops the table from drifting into ad-hoc shapes.
// ───────────────────────────────────────────────────────────────────────

/** `{ declared, computed }` — hash/value comparisons where both sides are
 *  reconstructed (tx body hash, script-integrity hash, PP-view hash, …). */
const Mismatch = <A, B>(inner: Schema.Codec<A, B>) => ({
  declared: inner,
  computed: inner,
});

/** `{ declared, actual }` — claimed network id vs. the cluster's network
 *  id (wrong-network family). */
const Mismatched = <A, B>(inner: Schema.Codec<A, B>) => ({
  declared: inner,
  actual: inner,
});

/** `{ declared, required }` — insufficient collateral / proposal deposit. */
const AtLeast = <A, B>(inner: Schema.Codec<A, B>) => ({
  declared: inner,
  required: inner,
});

/** `{ declared, minimum }` — fee-too-small, expiration-epoch-too-small. */
const AtLeastMin = <A, B>(inner: Schema.Codec<A, B>) => ({
  declared: inner,
  minimum: inner,
});

/** `{ declared, limit }` — size / ex-units / collateral-input count caps. */
const AtMost = <A, B>(inner: Schema.Codec<A, B>) => ({
  declared: inner,
  limit: inner,
});

// ═══════════════════════════════════════════════════════════════════════
// UTXOW layer — 19 predicates (Utxow.hs:76, tags 0-18)
// ═══════════════════════════════════════════════════════════════════════

const UtxowPredicateFields = [
  // Shelley base (tags 0-9, reused through all eras)
  Schema.TaggedStruct("UtxoFailure", { inner: Schema.String }), // 0
  Schema.TaggedStruct("InvalidWitnessesUTXOW", { keyHashes: HashList }), // 1
  Schema.TaggedStruct("MissingVKeyWitnessesUTXOW", { keyHashes: HashList }), // 2
  Schema.TaggedStruct("MissingScriptWitnessesUTXOW", { scriptHashes: HashList }), // 3
  Schema.TaggedStruct("ScriptWitnessNotValidatingUTXOW", { scriptHashes: HashList }), // 4
  Schema.TaggedStruct("MissingTxBodyMetadataHash", { hash: Hash }), // 5
  Schema.TaggedStruct("MissingTxMetadata", { hash: Hash }), // 6
  Schema.TaggedStruct("ConflictingMetadataHash", Mismatch(Hash)), // 7
  Schema.TaggedStruct("InvalidMetadata", {}), // 8
  Schema.TaggedStruct("ExtraneousScriptWitnessesUTXOW", { scriptHashes: HashList }), // 9
  // Alonzo additions (tags 10-15)
  Schema.TaggedStruct("MissingRedeemers", { pointers: StringList }), // 10
  Schema.TaggedStruct("MissingRequiredDatums", { dataHashes: HashList }), // 11
  Schema.TaggedStruct("NotAllowedSupplementalDatums", {
    acceptable: HashList,
    extraneous: HashList,
  }), // 12
  Schema.TaggedStruct("PPViewHashesDontMatch", Mismatch(Hash)), // 13
  Schema.TaggedStruct("UnspendableUTxONoDatumHash", { txIns: StringList }), // 14
  Schema.TaggedStruct("ExtraRedeemers", { pointers: StringList }), // 15
  // Babbage additions (tags 16-17)
  Schema.TaggedStruct("MalformedScriptWitnesses", { scriptHashes: HashList }), // 16
  Schema.TaggedStruct("MalformedReferenceScripts", { scriptHashes: HashList }), // 17
  // Conway v11+ addition (tag 18)
  Schema.TaggedStruct("ScriptIntegrityHashMismatch", Mismatch(Hash)), // 18
] as const;

export const ConwayUtxowPredFailure = Schema.Union(UtxowPredicateFields).pipe(
  Schema.toTaggedUnion("_tag"),
);
export type ConwayUtxowPredFailure = typeof ConwayUtxowPredFailure.Type;

// ═══════════════════════════════════════════════════════════════════════
// UTXO layer — 23 predicates (Utxo.hs:92-164, tags 0-22)
// ═══════════════════════════════════════════════════════════════════════

const UtxoPredicateFields = [
  // Shelley base
  Schema.TaggedStruct("UtxosFailure", { inner: Schema.String }), // 0
  Schema.TaggedStruct("BadInputsUTxO", { txIns: StringList }), // 1
  Schema.TaggedStruct("OutsideValidityIntervalUTxO", {
    interval: Schema.String,
    currentSlot: SlotNo,
  }), // 2
  Schema.TaggedStruct("MaxTxSizeUTxO", AtMost(Schema.Number)), // 3
  Schema.TaggedStruct("InputSetEmptyUTxO", {}), // 4
  Schema.TaggedStruct("FeeTooSmallUTxO", AtLeastMin(Lovelace)), // 5
  Schema.TaggedStruct("ValueNotConservedUTxO", {
    consumed: Schema.String,
    produced: Schema.String,
  }), // 6
  Schema.TaggedStruct("WrongNetwork", Mismatched(NetworkId)), // 7
  Schema.TaggedStruct("WrongNetworkWithdrawal", { declared: NetworkId }), // 8
  Schema.TaggedStruct("OutputTooSmallUTxO", { outputs: StringList }), // 9
  Schema.TaggedStruct("OutputBootAddrAttrsTooBig", { outputs: StringList }), // 10
  // Alonzo
  Schema.TaggedStruct("OutputTooBigUTxO", { outputs: StringList }), // 11
  // 12 — Alonzo/Utxo.hs:341-354: balance*100 >= txfee*collPerc
  Schema.TaggedStruct("InsufficientCollateral", AtLeast(Lovelace)),
  Schema.TaggedStruct("ScriptsNotPaidUTxO", { offenders: StringList }), // 13
  Schema.TaggedStruct("ExUnitsTooBigUTxO", AtMost(Schema.String)), // 14
  Schema.TaggedStruct("CollateralContainsNonADA", { nonAda: Schema.String }), // 15
  Schema.TaggedStruct("WrongNetworkInTxBody", Mismatched(NetworkId)), // 16
  Schema.TaggedStruct("OutsideForecast", { currentSlot: SlotNo }), // 17
  Schema.TaggedStruct("TooManyCollateralInputs", AtMost(Schema.Number)), // 18
  Schema.TaggedStruct("NoCollateralInputs", {}), // 19
  Schema.TaggedStruct("IncorrectTotalCollateralField", Mismatch(Lovelace)), // 20
  // Babbage
  Schema.TaggedStruct("BabbageOutputTooSmallUTxO", { outputs: StringList }), // 21
  Schema.TaggedStruct("BabbageNonDisjointRefInputs", { txIns: StringList }), // 22
] as const;

export const ConwayUtxoPredFailure = Schema.Union(UtxoPredicateFields).pipe(
  Schema.toTaggedUnion("_tag"),
);
export type ConwayUtxoPredFailure = typeof ConwayUtxoPredFailure.Type;

// ═══════════════════════════════════════════════════════════════════════
// UTXOS layer — 2 predicates (Utxos.hs:83-95, tags 0-1)
// ═══════════════════════════════════════════════════════════════════════

const UtxosPredicateFields = [
  Schema.TaggedStruct("ValidationTagMismatch", Mismatched(Schema.Boolean)), // 0
  Schema.TaggedStruct("CollectErrors", { errors: StringList }), // 1
] as const;

export const ConwayUtxosPredFailure = Schema.Union(UtxosPredicateFields).pipe(
  Schema.toTaggedUnion("_tag"),
);
export type ConwayUtxosPredFailure = typeof ConwayUtxosPredFailure.Type;

// ═══════════════════════════════════════════════════════════════════════
// GOV layer — 19 predicates (Gov.hs:179-220, tags 0-18)
// ═══════════════════════════════════════════════════════════════════════

const GovPredicateFields = [
  Schema.TaggedStruct("GovActionsDoNotExist", { ids: HashList }), // 0
  Schema.TaggedStruct("MalformedProposal", { action: Schema.String }), // 1
  Schema.TaggedStruct("ProposalProcedureNetworkIdMismatch", Mismatched(NetworkId)), // 2
  Schema.TaggedStruct("TreasuryWithdrawalsNetworkIdMismatch", Mismatched(NetworkId)), // 3
  Schema.TaggedStruct("ProposalDepositIncorrect", AtLeast(Lovelace)), // 4
  Schema.TaggedStruct("DisallowedVoters", { voters: StringList }), // 5
  Schema.TaggedStruct("ConflictingCommitteeUpdate", { members: StringList }), // 6
  Schema.TaggedStruct("ExpirationEpochTooSmall", AtLeastMin(EpochNo)), // 7
  Schema.TaggedStruct("InvalidPrevGovActionId", { proposal: Schema.String }), // 8
  Schema.TaggedStruct("VotingOnExpiredGovAction", { votes: StringList }), // 9
  Schema.TaggedStruct("ProposalCantFollow", {
    newer: Schema.String,
    older: Schema.String,
  }), // 10
  Schema.TaggedStruct("InvalidGuardrailsScriptHash", { hash: Hash }), // 11
  Schema.TaggedStruct("DisallowedProposalDuringBootstrap", { proposal: Schema.String }), // 12
  Schema.TaggedStruct("DisallowedVotesDuringBootstrap", { votes: StringList }), // 13
  Schema.TaggedStruct("VotersDoNotExist", { voters: StringList }), // 14
  Schema.TaggedStruct("ZeroTreasuryWithdrawals", { proposal: Schema.String }), // 15
  Schema.TaggedStruct("ProposalReturnAccountDoesNotExist", { account: Schema.String }), // 16
  Schema.TaggedStruct("TreasuryWithdrawalReturnAccountsDoNotExist", {
    accounts: StringList,
  }), // 17
  Schema.TaggedStruct("UnelectedCommitteeVoters", { voters: StringList }), // 18
] as const;

export const ConwayGovPredFailure = Schema.Union(GovPredicateFields).pipe(
  Schema.toTaggedUnion("_tag"),
);
export type ConwayGovPredFailure = typeof ConwayGovPredFailure.Type;

// ═══════════════════════════════════════════════════════════════════════
// MempoolRuleError — unified tagged union over all 4 layers (63 tags)
// ═══════════════════════════════════════════════════════════════════════

export const MempoolRuleError = Schema.Union([
  ...UtxowPredicateFields,
  ...UtxoPredicateFields,
  ...UtxosPredicateFields,
  ...GovPredicateFields,
]).pipe(Schema.toTaggedUnion("_tag"));
export type MempoolRuleError = typeof MempoolRuleError.Type;

// ───────────────────────────────────────────────────────────────────────
// Per-layer predicate counts — TS literal types anchor the values so
// adding/removing a `Schema.TaggedStruct` in the layer's array and
// forgetting to update the count fails `tsgo`, not just vitest.
// ───────────────────────────────────────────────────────────────────────

export const UTXOW_PREDICATE_COUNT: 19 = UtxowPredicateFields.length;
export const UTXO_PREDICATE_COUNT: 23 = UtxoPredicateFields.length;
export const UTXOS_PREDICATE_COUNT: 2 = UtxosPredicateFields.length;
export const GOV_PREDICATE_COUNT: 19 = GovPredicateFields.length;
export const CONWAY_PREDICATE_TOTAL =
  UTXOW_PREDICATE_COUNT + UTXO_PREDICATE_COUNT + UTXOS_PREDICATE_COUNT + GOV_PREDICATE_COUNT;
