/**
 * Conway UTXOW rule catalogue — failure-predicate surface.
 *
 * Wave-2 Correction #11: Conway's total failure surface is **63 predicates
 * across 4 layers**, not 19 in one type as the plan initially suggested:
 *   - ConwayUtxowPredFailure: 19 (tags 0-18)
 *   - ConwayUtxoPredFailure:  23 (tags 0-22)
 *   - ConwayUtxosPredFailure:  2 (tags 0-1)
 *   - ConwayGovPredFailure:   19 (tags 0-18)
 *
 * This file ships the **typed error surface** — a tagged-union of every
 * predicate — without the rule implementations. Implementations land
 * incrementally; callers can dispatch on `_tag` today and pattern-match
 * every variant exhaustively via `MempoolRuleError.match`.
 *
 * Each predicate is modelled as a `Schema.TaggedStruct` so it can (a) be
 * serialised across the ValidationClient RPC boundary, (b) generated by
 * `Schema.toArbitrary` for Conway §21 property tests, (c) decoded out of
 * Haskell node diagnostic streams for cross-checking.
 *
 * Source of truth (verified 2026-04-22 wave-2):
 *   ~/code/reference/IntersectMBO/cardano-ledger/eras/conway/impl/src/
 *     Cardano/Ledger/Conway/Rules/{Utxow,Utxo,Utxos,Gov}.hs
 */
import { Schema } from "effect";

// ═══════════════════════════════════════════════════════════════════════
// UTXOW layer — 19 predicates (Utxow.hs:76, tags 0-18)
// ═══════════════════════════════════════════════════════════════════════

const UtxowPredicateFields = [
  // Shelley base (tags 0-9, reused through all eras)
  Schema.TaggedStruct("UtxoFailure", { inner: Schema.String }), // 0
  Schema.TaggedStruct("InvalidWitnessesUTXOW", { keyHashes: Schema.Array(Schema.Uint8Array) }), // 1
  Schema.TaggedStruct("MissingVKeyWitnessesUTXOW", {
    keyHashes: Schema.Array(Schema.Uint8Array),
  }), // 2
  Schema.TaggedStruct("MissingScriptWitnessesUTXOW", {
    scriptHashes: Schema.Array(Schema.Uint8Array),
  }), // 3
  Schema.TaggedStruct("ScriptWitnessNotValidatingUTXOW", {
    scriptHashes: Schema.Array(Schema.Uint8Array),
  }), // 4
  Schema.TaggedStruct("MissingTxBodyMetadataHash", { hash: Schema.Uint8Array }), // 5
  Schema.TaggedStruct("MissingTxMetadata", { hash: Schema.Uint8Array }), // 6
  Schema.TaggedStruct("ConflictingMetadataHash", {
    declared: Schema.Uint8Array,
    computed: Schema.Uint8Array,
  }), // 7
  Schema.TaggedStruct("InvalidMetadata", {}), // 8
  Schema.TaggedStruct("ExtraneousScriptWitnessesUTXOW", {
    scriptHashes: Schema.Array(Schema.Uint8Array),
  }), // 9
  // Alonzo additions (tags 10-15)
  Schema.TaggedStruct("MissingRedeemers", { pointers: Schema.Array(Schema.String) }), // 10
  Schema.TaggedStruct("MissingRequiredDatums", { dataHashes: Schema.Array(Schema.Uint8Array) }), // 11
  Schema.TaggedStruct("NotAllowedSupplementalDatums", {
    acceptable: Schema.Array(Schema.Uint8Array),
    extraneous: Schema.Array(Schema.Uint8Array),
  }), // 12
  Schema.TaggedStruct("PPViewHashesDontMatch", {
    declared: Schema.Uint8Array,
    computed: Schema.Uint8Array,
  }), // 13
  Schema.TaggedStruct("UnspendableUTxONoDatumHash", { txIns: Schema.Array(Schema.String) }), // 14
  Schema.TaggedStruct("ExtraRedeemers", { pointers: Schema.Array(Schema.String) }), // 15
  // Babbage additions (tags 16-17)
  Schema.TaggedStruct("MalformedScriptWitnesses", {
    scriptHashes: Schema.Array(Schema.Uint8Array),
  }), // 16
  Schema.TaggedStruct("MalformedReferenceScripts", {
    scriptHashes: Schema.Array(Schema.Uint8Array),
  }), // 17
  // Conway v11+ addition (tag 18)
  Schema.TaggedStruct("ScriptIntegrityHashMismatch", {
    declared: Schema.Uint8Array,
    computed: Schema.Uint8Array,
  }), // 18
] as const;

export const ConwayUtxowPredFailure = Schema.Union(UtxowPredicateFields).pipe(
  Schema.toTaggedUnion("_tag"),
);
export type ConwayUtxowPredFailure = typeof ConwayUtxowPredFailure.Type;

// ═══════════════════════════════════════════════════════════════════════
// UTXO layer — 23 predicates (Utxo.hs:92-164, tags 0-22)
// ═══════════════════════════════════════════════════════════════════════

const UtxoPredicateFields = [
  // Shelley base
  Schema.TaggedStruct("UtxosFailure", { inner: Schema.String }), // 0
  Schema.TaggedStruct("BadInputsUTxO", { txIns: Schema.Array(Schema.String) }), // 1
  Schema.TaggedStruct("OutsideValidityIntervalUTxO", {
    interval: Schema.String,
    currentSlot: Schema.BigInt,
  }), // 2
  Schema.TaggedStruct("MaxTxSizeUTxO", { declared: Schema.Number, limit: Schema.Number }), // 3
  Schema.TaggedStruct("InputSetEmptyUTxO", {}), // 4
  Schema.TaggedStruct("FeeTooSmallUTxO", {
    declared: Schema.BigInt,
    minimum: Schema.BigInt,
  }), // 5
  Schema.TaggedStruct("ValueNotConservedUTxO", {
    consumed: Schema.String,
    produced: Schema.String,
  }), // 6
  Schema.TaggedStruct("WrongNetwork", {
    declared: Schema.Number,
    actual: Schema.Number,
  }), // 7
  Schema.TaggedStruct("WrongNetworkWithdrawal", { declared: Schema.Number }), // 8
  Schema.TaggedStruct("OutputTooSmallUTxO", { outputs: Schema.Array(Schema.String) }), // 9
  Schema.TaggedStruct("OutputBootAddrAttrsTooBig", { outputs: Schema.Array(Schema.String) }), // 10
  // Alonzo
  Schema.TaggedStruct("OutputTooBigUTxO", { outputs: Schema.Array(Schema.String) }), // 11
  Schema.TaggedStruct("InsufficientCollateral", {
    declared: Schema.BigInt,
    required: Schema.BigInt,
  }), // 12 — Alonzo/Utxo.hs:341-354: balance*100 >= txfee*collPerc
  Schema.TaggedStruct("ScriptsNotPaidUTxO", { offenders: Schema.Array(Schema.String) }), // 13
  Schema.TaggedStruct("ExUnitsTooBigUTxO", { declared: Schema.String, limit: Schema.String }), // 14
  Schema.TaggedStruct("CollateralContainsNonADA", { nonAda: Schema.String }), // 15
  Schema.TaggedStruct("WrongNetworkInTxBody", {
    declared: Schema.Number,
    actual: Schema.Number,
  }), // 16
  Schema.TaggedStruct("OutsideForecast", { currentSlot: Schema.BigInt }), // 17
  Schema.TaggedStruct("TooManyCollateralInputs", { declared: Schema.Number, limit: Schema.Number }), // 18
  Schema.TaggedStruct("NoCollateralInputs", {}), // 19
  Schema.TaggedStruct("IncorrectTotalCollateralField", {
    declared: Schema.BigInt,
    computed: Schema.BigInt,
  }), // 20
  // Babbage
  Schema.TaggedStruct("BabbageOutputTooSmallUTxO", { outputs: Schema.Array(Schema.String) }), // 21
  Schema.TaggedStruct("BabbageNonDisjointRefInputs", { txIns: Schema.Array(Schema.String) }), // 22
] as const;

export const ConwayUtxoPredFailure = Schema.Union(UtxoPredicateFields).pipe(
  Schema.toTaggedUnion("_tag"),
);
export type ConwayUtxoPredFailure = typeof ConwayUtxoPredFailure.Type;

// ═══════════════════════════════════════════════════════════════════════
// UTXOS layer — 2 predicates (Utxos.hs:83-95, tags 0-1)
// ═══════════════════════════════════════════════════════════════════════

const UtxosPredicateFields = [
  Schema.TaggedStruct("ValidationTagMismatch", {
    declared: Schema.Boolean,
    actual: Schema.Boolean,
  }), // 0
  Schema.TaggedStruct("CollectErrors", { errors: Schema.Array(Schema.String) }), // 1
] as const;

export const ConwayUtxosPredFailure = Schema.Union(UtxosPredicateFields).pipe(
  Schema.toTaggedUnion("_tag"),
);
export type ConwayUtxosPredFailure = typeof ConwayUtxosPredFailure.Type;

// ═══════════════════════════════════════════════════════════════════════
// GOV layer — 19 predicates (Gov.hs:179-220, tags 0-18)
// ═══════════════════════════════════════════════════════════════════════

const GovPredicateFields = [
  Schema.TaggedStruct("GovActionsDoNotExist", { ids: Schema.Array(Schema.Uint8Array) }), // 0
  Schema.TaggedStruct("MalformedProposal", { action: Schema.String }), // 1
  Schema.TaggedStruct("ProposalProcedureNetworkIdMismatch", {
    declared: Schema.Number,
    actual: Schema.Number,
  }), // 2
  Schema.TaggedStruct("TreasuryWithdrawalsNetworkIdMismatch", {
    declared: Schema.Number,
    actual: Schema.Number,
  }), // 3
  Schema.TaggedStruct("ProposalDepositIncorrect", {
    declared: Schema.BigInt,
    required: Schema.BigInt,
  }), // 4
  Schema.TaggedStruct("DisallowedVoters", { voters: Schema.Array(Schema.String) }), // 5
  Schema.TaggedStruct("ConflictingCommitteeUpdate", { members: Schema.Array(Schema.String) }), // 6
  Schema.TaggedStruct("ExpirationEpochTooSmall", {
    declared: Schema.BigInt,
    minimum: Schema.BigInt,
  }), // 7
  Schema.TaggedStruct("InvalidPrevGovActionId", { proposal: Schema.String }), // 8
  Schema.TaggedStruct("VotingOnExpiredGovAction", { votes: Schema.Array(Schema.String) }), // 9
  Schema.TaggedStruct("ProposalCantFollow", {
    newer: Schema.String,
    older: Schema.String,
  }), // 10
  Schema.TaggedStruct("InvalidGuardrailsScriptHash", { hash: Schema.Uint8Array }), // 11
  Schema.TaggedStruct("DisallowedProposalDuringBootstrap", { proposal: Schema.String }), // 12
  Schema.TaggedStruct("DisallowedVotesDuringBootstrap", { votes: Schema.Array(Schema.String) }), // 13
  Schema.TaggedStruct("VotersDoNotExist", { voters: Schema.Array(Schema.String) }), // 14
  Schema.TaggedStruct("ZeroTreasuryWithdrawals", { proposal: Schema.String }), // 15
  Schema.TaggedStruct("ProposalReturnAccountDoesNotExist", { account: Schema.String }), // 16
  Schema.TaggedStruct("TreasuryWithdrawalReturnAccountsDoNotExist", {
    accounts: Schema.Array(Schema.String),
  }), // 17
  Schema.TaggedStruct("UnelectedCommitteeVoters", { voters: Schema.Array(Schema.String) }), // 18
] as const;

export const ConwayGovPredFailure = Schema.Union(GovPredicateFields).pipe(
  Schema.toTaggedUnion("_tag"),
);
export type ConwayGovPredFailure = typeof ConwayGovPredFailure.Type;

// ═══════════════════════════════════════════════════════════════════════
// MempoolRuleError — unified tagged union over all 4 layers (63 tags)
// ═══════════════════════════════════════════════════════════════════════

export const MempoolRuleError = Schema.Union([
  ...UtxowPredicateFields,
  ...UtxoPredicateFields,
  ...UtxosPredicateFields,
  ...GovPredicateFields,
]).pipe(Schema.toTaggedUnion("_tag"));
export type MempoolRuleError = typeof MempoolRuleError.Type;

/** Count invariants — tracked in tests. */
export const UTXOW_PREDICATE_COUNT = 19;
export const UTXO_PREDICATE_COUNT = 23;
export const UTXOS_PREDICATE_COUNT = 2;
export const GOV_PREDICATE_COUNT = 19;
export const CONWAY_PREDICATE_TOTAL =
  UTXOW_PREDICATE_COUNT + UTXO_PREDICATE_COUNT + UTXOS_PREDICATE_COUNT + GOV_PREDICATE_COUNT;
